# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /etc/letsencrypt/archive/15-puzzle.mellonis.ru
cert = /etc/letsencrypt/live/15-puzzle.mellonis.ru/cert.pem
privkey = /etc/letsencrypt/live/15-puzzle.mellonis.ru/privkey.pem
chain = /etc/letsencrypt/live/15-puzzle.mellonis.ru/chain.pem
fullchain = /etc/letsencrypt/live/15-puzzle.mellonis.ru/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = b0da99910c74e46a1f578aa424704a5e
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
15-puzzle.mellonis.ru = /var/www/certbot
